phpSettings:
  display_startup_errors:     true
  display_errors:             true
  max_execution_time:         60
  date.timezone:              'Europe/London'
  mbstring.internal_encoding: 'UTF-8'

view_manager:
  display_not_found_reason:     true
  display_exceptions:           true
  doctype:                      'HTML5'
  not_found_template:           'error/404'
  exception_template:           'error/index'
  strategies:                   ['ViewJsonStrategy']
  stack:
    script_paths:                 ['view']
  template_map:
    layout/layout:              'view/layout/layout.phtml'
    layout/error-layout:        'view/error/layout.phtml'
    index/index:                'view/main/index/index.phtml'
    error/404:                  'view/error/404.phtml'
    error/index:                'view/error/index.phtml'